---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /path/to/radarr/data:/config
      - /home/umbrel/umbrel/data/storage/downloads/movies/:/movies #optional
      - /home/umbrel/umbrel/data/storage/downloads/qbit:/home/umbrel/umbrel/data/storage/downloads/qbit #optional
    ports:
      - 7879:7878
    restart: unless-stopped
